// ============================================================
// MOCK DATA — for placeholder API implementations only.
// Remove this file when you connect your real Spring Boot API.
// ============================================================

export const mockAirlines = [
  { id: 1, name: 'SkyJet Airways', code: 'SJ', logo: 'SJ', country: 'United States' },
  { id: 2, name: 'BlueOcean Airlines', code: 'BO', logo: 'BO', country: 'United Kingdom' },
  { id: 3, name: 'Pacific Express', code: 'PX', logo: 'PX', country: 'Singapore' },
  { id: 4, name: 'Emirate Crown', code: 'EC', logo: 'EC', country: 'United Arab Emirates' },
  { id: 5, name: 'Nippon Wings', code: 'NW', logo: 'NW', country: 'Japan' },
  { id: 6, name: 'Air Velocity', code: 'AV', logo: 'AV', country: 'France' },
];

export const mockAirports = [
  { code: 'JFK', name: 'John F. Kennedy International', city: 'New York', country: 'USA' },
  { code: 'LHR', name: 'Heathrow Airport', city: 'London', country: 'UK' },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France' },
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE' },
  { code: 'SIN', name: 'Changi Airport', city: 'Singapore', country: 'Singapore' },
  { code: 'HND', name: 'Haneda Airport', city: 'Tokyo', country: 'Japan' },
  { code: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'USA' },
  { code: 'ORD', name: "O'Hare International", city: 'Chicago', country: 'USA' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International', city: 'Mumbai', country: 'India' },
  { code: 'DEL', name: 'Indira Gandhi International', city: 'Delhi', country: 'India' },
  { code: 'SYD', name: 'Kingsford Smith Airport', city: 'Sydney', country: 'Australia' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany' },
];

export const mockFlights = [
  {
    id: 101,
    flightNumber: 'SJ201',
    airlineId: 1,
    departureAirportCode: 'JFK',
    arrivalAirportCode: 'LHR',
    departureTime: '08:00',
    arrivalTime: '20:00',
    economyPrice: 450,
    premiumEconomyPrice: 780,
    businessPrice: 1850,
    economySeats: 45,
    premiumEconomySeats: 20,
    businessSeats: 8,
    status: 'SCHEDULED',
  },
  {
    id: 102,
    flightNumber: 'BO302',
    airlineId: 2,
    departureAirportCode: 'JFK',
    arrivalAirportCode: 'LHR',
    departureTime: '10:30',
    arrivalTime: '22:45',
    economyPrice: 420,
    premiumEconomyPrice: 720,
    businessPrice: 1600,
    economySeats: 60,
    premiumEconomySeats: 25,
    businessSeats: 12,
    status: 'SCHEDULED',
  },
  {
    id: 103,
    flightNumber: 'AV403',
    airlineId: 6,
    departureAirportCode: 'JFK',
    arrivalAirportCode: 'CDG',
    departureTime: '21:15',
    arrivalTime: '10:30',
    economyPrice: 390,
    premiumEconomyPrice: 680,
    businessPrice: 1450,
    economySeats: 80,
    premiumEconomySeats: 30,
    businessSeats: 15,
    status: 'SCHEDULED',
  },
  {
    id: 104,
    flightNumber: 'EC504',
    airlineId: 4,
    departureAirportCode: 'JFK',
    arrivalAirportCode: 'DXB',
    departureTime: '14:00',
    arrivalTime: '11:30',
    economyPrice: 620,
    premiumEconomyPrice: 1050,
    businessPrice: 2800,
    economySeats: 50,
    premiumEconomySeats: 22,
    businessSeats: 10,
    status: 'SCHEDULED',
  },
  {
    id: 105,
    flightNumber: 'PX605',
    airlineId: 3,
    departureAirportCode: 'LHR',
    arrivalAirportCode: 'SIN',
    departureTime: '09:00',
    arrivalTime: '05:30',
    economyPrice: 550,
    premiumEconomyPrice: 920,
    businessPrice: 2100,
    economySeats: 65,
    premiumEconomySeats: 28,
    businessSeats: 14,
    status: 'SCHEDULED',
  },
  {
    id: 106,
    flightNumber: 'NW706',
    airlineId: 5,
    departureAirportCode: 'SIN',
    arrivalAirportCode: 'HND',
    departureTime: '16:00',
    arrivalTime: '23:50',
    economyPrice: 320,
    premiumEconomyPrice: 560,
    businessPrice: 1250,
    economySeats: 90,
    premiumEconomySeats: 35,
    businessSeats: 18,
    status: 'SCHEDULED',
  },
  {
    id: 107,
    flightNumber: 'SJ807',
    airlineId: 1,
    departureAirportCode: 'LAX',
    arrivalAirportCode: 'ORD',
    departureTime: '07:00',
    arrivalTime: '13:15',
    economyPrice: 280,
    premiumEconomyPrice: 480,
    businessPrice: 980,
    economySeats: 100,
    premiumEconomySeats: 40,
    businessSeats: 20,
    status: 'SCHEDULED',
  },
  {
    id: 108,
    flightNumber: 'BO908',
    airlineId: 2,
    departureAirportCode: 'DXB',
    arrivalAirportCode: 'BOM',
    departureTime: '12:00',
    arrivalTime: '16:45',
    economyPrice: 240,
    premiumEconomyPrice: 420,
    businessPrice: 890,
    economySeats: 75,
    premiumEconomySeats: 30,
    businessSeats: 16,
    status: 'SCHEDULED',
  },
  {
    id: 109,
    flightNumber: 'AV109',
    airlineId: 6,
    departureAirportCode: 'CDG',
    arrivalAirportCode: 'FRA',
    departureTime: '06:30',
    arrivalTime: '08:00',
    economyPrice: 180,
    premiumEconomyPrice: 320,
    businessPrice: 680,
    economySeats: 120,
    premiumEconomySeats: 45,
    businessSeats: 22,
    status: 'SCHEDULED',
  },
  {
    id: 110,
    flightNumber: 'PX210',
    airlineId: 3,
    departureAirportCode: 'DEL',
    arrivalAirportCode: 'SIN',
    departureTime: '23:00',
    arrivalTime: '06:15',
    economyPrice: 310,
    premiumEconomyPrice: 540,
    businessPrice: 1180,
    economySeats: 85,
    premiumEconomySeats: 32,
    businessSeats: 14,
    status: 'SCHEDULED',
  },
  {
    id: 111,
    flightNumber: 'EC311',
    airlineId: 4,
    departureAirportCode: 'DXB',
    arrivalAirportCode: 'SYD',
    departureTime: '10:15',
    arrivalTime: '06:00',
    economyPrice: 680,
    premiumEconomyPrice: 1150,
    businessPrice: 2950,
    economySeats: 55,
    premiumEconomySeats: 24,
    businessSeats: 11,
    status: 'SCHEDULED',
  },
  {
    id: 112,
    flightNumber: 'NW412',
    airlineId: 5,
    departureAirportCode: 'HND',
    arrivalAirportCode: 'LAX',
    departureTime: '17:45',
    arrivalTime: '11:30',
    economyPrice: 590,
    premiumEconomyPrice: 980,
    businessPrice: 2300,
    economySeats: 70,
    premiumEconomySeats: 30,
    businessSeats: 15,
    status: 'SCHEDULED',
  },
];
